language: node_js

node_js: ["8", "10", "12"]

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - libqrencode-dev
            - libpng12-dev
            - libjpeg-dev

env:
    - CXX=g++-4.8
